### ISSUE TITLE
Missing item level component

### ISSUE THREAD

**Issue by hubgogo** [Sattva-108/AdiBags-WoTLK-3.3.5#1]
I use another author's
AdiBags has an item level display as shown below:
![2023-04-13_092109](https://user-images.githubusercontent.com/91697479/231621691-52de7018-3a2d-4425-9db9-757e5e03e514.png)

And your AdiBags don't have item level components

As shown below:

![2023-04-13_093124](https://user-images.githubusercontent.com/91697479/231622906-70b82778-d1ec-4f6f-907d-e485da64f347.png)

**Comment by Sattva-108** [comment]
Thank you, ItemLevel module is added! 

![wow_beyM3Isauc](https://user-images.githubusercontent.com/74269253/232476747-930de2d1-d42f-4f14-b9b5-58c0de9a1af6.png)
