### ISSUE TITLE
Adding items to manual categories causes this lua error

### ISSUE THREAD

**Issue by Szyler** [Sattva-108/AdiBags-WoTLK-3.3.5#15]
https://i.imgur.com/Xvm6l0q.png

Error occured in: Global
Count: 1
Message: memory allocation error: block too big
Debug:
   (tail call): ?
   AdiBags\Utility.lua:57:
      AdiBags\Utility.lua:53
   (tail call): ?
   AdiBags\AdiBags.lua:1243: Filter()
   AdiBags\widgets\ContainerFrame.lua:947: FilterSlot()
   AdiBags\widgets\ContainerFrame.lua:956: DispatchItem()
   AdiBags\widgets\ContainerFrame.lua:1061: RedispatchAllItems()
   AdiBags\widgets\ContainerFrame.lua:666:
      AdiBags\widgets\ContainerFrame.lua:660
   ...braryXML\CallbackHandler-1.0\CallbackHandler-1.0.lua:155:
      ...braryXML\CallbackHandler-1.0\CallbackHandler-1.0.lua:155
   [string "safecall Dispatcher[1]"]:4:
      [string "safecall Dispatcher[1]"]:4
   [C]: ?
   ..\SharedXML\Util\SharedOverwrites.lua:85:
      ..\SharedXML\Util\SharedOverwrites.lua:81
   [string "safecall Dispatcher[1]"]:13: ?()
   ...braryXML\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: SendMessage()
   AdiBags\modules\FilterOverride.lua:71: AssignItems()
   AdiBags\modules\FilterOverride.lua:341: ?()
   ...braryXML\CallbackHandler-1.0\CallbackHandler-1.0.lua:145:
      ...braryXML\CallbackHandler-1.0\CallbackHandler-1.0.lua:145
   [string "safecall Dispatcher[2]"]:4:
      [string "safecall Dispatcher[2]"]:4
   [C]: ?
   ..\SharedXML\Util\SharedOverwrites.lua:85:
      ..\SharedXML\Util\SharedOverwrites.lua:81
   [string "safecall Dispatcher[2]"]:13: ?()
   ...braryXML\CallbackHandler-1.0\CallbackHandler-1.0.lua:90:
      ...braryXML\CallbackHandler-1.0\CallbackHandler-1.0.lua:85
   (tail call): ?

**Comment by Szyler** [comment]
similarly, moving an item from bag to bank:
https://i.imgur.com/4WVg3JT.jpeg

Message: memory allocation error: block too big
Debug:
   (tail call): ?
   AdiBags\Utility.lua:57:
      AdiBags\Utility.lua:53
   (tail call): ?
   AdiBags\AdiBags.lua:1243: Filter()
   AdiBags\widgets\ContainerFrame.lua:947: FilterSlot()
   AdiBags\widgets\ContainerFrame.lua:956: DispatchItem()
   AdiBags\widgets\ContainerFrame.lua:1061: RedispatchAllItems()
   AdiBags\widgets\ContainerFrame.lua:666:
      AdiBags\widgets\ContainerFrame.lua:660
   ...braryXML\CallbackHandler-1.0\CallbackHandler-1.0.lua:155:
      ...braryXML\CallbackHandler-1.0\CallbackHandler-1.0.lua:155
   [string "safecall Dispatcher[1]"]:4:
      [string "safecall Dispatcher[1]"]:4
   [C]: ?
   ..\SharedXML\Util\SharedOverwrites.lua:85:
      ..\SharedXML\Util\SharedOverwrites.lua:81
   [string "safecall Dispatcher[1]"]:13: ?()
   ...braryXML\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: SendMessage()
   AdiBags\modules\NewItemTracking.lua:303:
      AdiBags\modules\NewItemTracking.lua:224
   (tail call): ?
   [C]: ?
   ..\SharedXML\Util\SharedOverwrites.lua:85:
      ..\SharedXML\Util\SharedOverwrites.lua:81
   (tail call): ?
   (tail call): ?
   ...\AddOns\AdiBags\libs\AceBucket-3.0\AceBucket-3.0.lua:116:
      ...\AddOns\AdiBags\libs\AceBucket-3.0\AceBucket-3.0.lua:109
   (tail call): ?
   [C]: ?
   ..\SharedXML\Util\SharedOverwrites.lua:85:
      ..\SharedXML\Util\SharedOverwrites.lua:81
   (tail call): ?
   (tail call): ?
   ..\LibraryXML\AceTimer-3.0\AceTimer-3.0.lua:309:
      ..\LibraryXML\AceTimer-3.0\AceTimer-3.0.lua:298

**Comment by Szyler** [comment]
and i think that crashed my game when i tried to /reload.

**Comment by Sattva-108** [comment]
Hey, I know you.
Is it Ascension server it's happening?

**Comment by Szyler** [comment]
yes its on Ascension

**Comment by Szyler** [comment]
I made my custom Ascension features into standalone plugins for adibags so i can use your downport.
This issue didn't seem to be Ascension related, so i figured i'd post here.

**Comment by Sattva-108** [comment]
> https://i.imgur.com/Xvm6l0q.png

https://github.com/Sattva-108/AdiBags-WoTLK-3.3.5/assets/74269253/18622905-735b-45c2-92c8-2097ab796069

**Comment by Sattva-108** [comment]
> similarly, moving an item from bag to bank:
> https://i.imgur.com/4WVg3JT.jpeg


https://github.com/Sattva-108/AdiBags-WoTLK-3.3.5/assets/74269253/f9eeef89-dac4-4c22-aab4-6a6724a64d6d

**Comment by Sattva-108** [comment]
i cannot reproduce it.
didn't see these errors happen yet.

i'm an active user or manual filtering, as well as some of my users.

**Comment by Sattva-108** [comment]
i did use manual filters on the Ascension as well. 

Can you try without the plugins you wrote?

**Comment by Sattva-108** [comment]
> move to manual category
> https://i.imgur.com/Xvm6l0q.png

i can see 2 category lists (on the screenshot you provided) -  is out of the AdiBags "frame"
this didn't happen to me, i don't remember.

could be server-side / plugin issue, that has to be fixed.
i will have to install ascension client first, to help you, if you can confirm it's not your newly-written plugins issue.

**Comment by Sattva-108** [comment]
i did use manual filters on the Ascension as well. 

Can you try without the plugins you wrote?

**Comment by Szyler** [comment]
I can't replicate it with or without my plugins. I will try to figure out a way to reproduce it.

**Comment by Szyler** [comment]
I found the issue. It was my function being slow, and causing increasing lag the more items were in a custom filter.
I've fixed it now and no longer get any issue.
