### ISSUE TITLE
Backpack window still cannot be moved in manual mode

### ISSUE THREAD

**Issue by hubgogo** [Sattva-108/AdiBags-WoTLK-3.3.5#2]
Hi, hello, I'm here to give feedback again
sorry there is still a problem
![3](https://user-images.githubusercontent.com/91697479/236679944-24df3769-21b5-4aaf-923e-2c9309d821e3.gif)

The version I use is free to move in manual mode

![4](https://user-images.githubusercontent.com/91697479/236680049-632e28b1-e3d3-4e14-bbcd-2afc368a64cb.gif)

**Comment by Sattva-108** [comment]
I put some time time to make it as perfect as i could!
By default it's Shift+Click to move bag in Manual mode now.
I added option, if you want on just Left-Click to move bag then choose option `Swap` in the `/ab `options.
I'm glad that someone is using this addon and helps me make it better, thank you for feedback!

![adibags](https://user-images.githubusercontent.com/74269253/237022963-a4888180-8c25-4ab9-a3f7-f04d33e36714.gif)

**Comment by hubgogo** [comment]
![1](https://github.com/Sattva-108/AdiBags-WoTLK-3.3.5/assets/91697479/4f738452-c2aa-4d97-bdba-5d5fab3863d1)

Great now, manual mode works.

Thanks
