### ISSUE TITLE
Sorry, I found an error

### ISSUE THREAD

**Issue by hubgogo** [Sattva-108/AdiBags-WoTLK-3.3.5#3]
**Alt-Left-Click**    Error after clicking

![QQ五笔截图未命名](https://github.com/Sattva-108/AdiBags-WoTLK-3.3.5/assets/91697479/26f64209-f5e8-4006-b3d3-dec7c2da61a6)

The error code is as follows:

1x AdiBags-3.3.5\AdiBags.lua:980: attempt to index global 'LibCompat' (a nil value)
AdiBags-3.3.5\widgets\ContainerFrame.lua:412: in function <AdiBags\widgets\ContainerFrame.lua:407>

Locals:
self = AdiBagsAnchor2 {
 name = "Backpack"
 label = "Backpack"
 target = AdiBagsContainer1 {}
 corner = <unnamed> {}
 0 = <userdata>
}
button = "LeftButton"
addon = <table> {
 AcquireItemButton = <function> @ AdiBags\widgets\ItemButton.lua:109:
 UnitHealthInfo = <function> @ AdiBags\libs\LibCompat-1.0\LibCompat-1.0.lua:392:
 CancelTimer = <function> @ AdiBags\libs\LibCompat-1.0\LibCompat-1.0.lua:616:
 SecureHook = <function> @ AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:339:
 WithinRangeExclusive = <function> @ AdiBags\libs\LibCompat-1.0\LibCompat-1.0.lua:196:
 WeakTable = <function> @ AdiBags\libs\LibCompat-1.0\LibCompat-1.0.lua:129:
 After = <function> @ AdiBags\libs\LibCompat-1.0\LibCompat-1.0.lua:599:
 defaultModulePrototype = <table> {}
 ConfigChanged = <function> @ AdiBags\AdiBags.lua:354:
 SetDefaultModulePrototype = <function> @ AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:425:
 EscapeStr = <function> @ AdiBags\libs\LibCompat-1.0\LibCompat-1.0.lua:716:
 Filter = <function> @ AdiBags\AdiBags.lua:1172:
 IsEnabled = <function> @ AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:467:
 Reconfigure = <function> @ AdiBags\AdiBags.lua:275:
 SetupTooltip = <function> @ AdiBags\Utility.lua:94:
 SafePack = <function> @ AdiBags\libs\LibCompat-1.0\LibCompat-1.0.lua:81:
 UnregisterMessage = <function> @ AdiBags\libs\LibCompat-1.0\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179:
 IsGroupInCombat = <function> @ AdiBags\libs\LibCompat-1.0\LibCompat-1.0.lua:319:
 hooks = <table> {}
 GetDistinctItemID = <function> @ AdiBags\Utility.lua:155:
 filterProto = <table> {}
 db = <table> {}
 OpenOptions = <function> @ AdiBags\Options.lua:603:
 SetEnabledState = <function> @ AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:440:
 UnitIsGroupAssistant = <function> @ AdiBags\libs\LibCompat-1.0\LibCompat-1.0.lua:464:
 IterateBags = <function> @ AdiBags\AdiBags.lua:724:
 GetSpecializationRole = <function> @ AdiBags\libs\LibCompat-1.0\LibCompat-1.0.lua:810:
 NewTimer = <function> @ AdiBags\libs\LibCompat-1.0\LibCompat-1.0.lua:608:
 HookBagFrameCreation = <function> @ AdiBags\AdiBags.lua:739:
 NewBag = <function> @ AdiBags\AdiBags.lua:691:
 WithinRange = <function> @ AdiBags\libs\LibCompat-1.0\LibCompat-1.0.lua:192:
 SetActiveSpecGroup = <function> defined =[C]:-1
 GetClassColorObj = <function> @ AdiBags\libs\LibCompat-1.0\LibCompat-1.0.lua:509:
 BACKDROP = <table> {}
 GetNumUnspentTalents = <function> defined =[C]:-1
 NewModule = <function> @ AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:256:
 InitializeFilters = <function> @ AdiBags\AdiBags.lua:1115:
 QuickDispatch = <function> @ AdiBags\libs\LibCompat-1.0\LibCompat-1.0.lua:65:
 IterateFilters = <function> @ AdiBags\AdiBags.lua:1148:
 anchor = AdiBagsAnchor1 {}
 CreateBagSlotPanel = <function> @ AdiBags\widgets\BagSlots.lua:403:
 TOP_PADDING = 32
 BI = <table> {}
 CanPutItemInContainer = <function> @ AdiBags\Utility.lua:179:
 OnProfileChanged = <function> @ AdiBags\AdiBags.lua:283:
 GetName = <function> @ AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:300:
 GetOptions = <function> @ AdiBags\Options.lua:236:
 UnitFullName = <function> @ AdiBags\libs\LibCompat-1.0\LibCompat-1.0.lua:416:
 OpenBackpack = <function> defined @Ad
  ---

**Comment by Sattva-108** [comment]
did you update all files i have changed? 
AdiBags.lua has the definition of LibCompat.
![firefox_cjX8XeryS4](https://github.com/Sattva-108/AdiBags-WoTLK-3.3.5/assets/74269253/c0d5219f-d1ec-4389-ba16-ff0a31a50fa3)

**Comment by Sattva-108** [comment]
sorry it was my mistake, i had libcompat to be loaded by exetrnal plugin.

fixed issue in this commit. you can just redownload AdiBags.lua or simply redownload the whole addon and it will be fixed!
https://github.com/Sattva-108/AdiBags-WoTLK-3.3.5/commit/7f1e7a1881a726e42e02e476617ecd3daac6f6d0
