### ISSUE TITLE
ContainerFrame.lua error 

### ISSUE THREAD

**Issue by Drakcain** [Sattva-108/AdiBags-WoTLK-3.3.5#6]
I am running a little modified version of Adibags on Ascension but was hoping you could possibly help me on solving the issue I am having with adibags. I provided 2 SS of what I am dealing with and I have several other errors that occur also with mutiple AdiBagsSections  17,25,23,18   each one of its own LUA error windows. Thanks in advanced if you can shed any light on this. 

![Screenshot_20240119_122837_Discord](https://github.com/Sattva-108/AdiBags-WoTLK-3.3.5/assets/82975622/eb556083-41fb-42b4-b74c-16b3882869bc)

![Screenshot_20240119_122915_Discord](https://github.com/Sattva-108/AdiBags-WoTLK-3.3.5/assets/82975622/3b069dc3-1137-49a8-b043-da2a8fb12cf4)

**Comment by Sattva-108** [comment]
It is really hard to blindly try to help you, as i:
1. Don't have Ascension client atm.
2. Don't have items you are trying to move.

I found one possible solution in this commit of official AdiBags. 
https://github.com/AdiAddons/AdiBags/commit/09e2b6ec25482fc54c4f777e9ad26ee48155997d#diff-169e6ef2f3fe0d0736dc009c3a719af2120ba7912256d54e95f1c5dc67fe4718R1020

It's not hard to implement this fix yourself, but if you struggle, better contact me in discord: **sattva108**

**Comment by Sattva-108** [comment]
if didn't help then need to follow this commit:

https://github.com/AdiAddons/AdiBags/commit/d20a85b2c867d732c6ea10b19b4ab3bc59f6d64f

**Comment by Drakcain** [comment]
I just implemented that first fix you suggested so we shall see.. Ill let you know the result ty. 

While in there tho It looked like it was modified alot more then I thought due to that line actually being up by 860
