### ISSUE TITLE
Custom filters dissapear from the list in the settings

### ISSUE THREAD

**Issue by tateomuro** [Sattva-108/AdiBags-WoTLK-3.3.5#8]
When I create custom filters using Cyrillic letters some of filters may dissapear from the list in the settings. These filters are work in bank and bag, but the only problem is they are not visible in Settings. For example I added filter with Section "Репутация Спореггар" and after added another filter with Section "Колода Зверей". The filter with Section "Репутация Спореггар" just dissapeared from the list. Sometimes adding some filters they dissapear by themself or make appear some of dissapeared filters.
After few days ago a tried to use only Latin letters and all appeared. But I would like to use Cyrillic if it possible. Could you check this problem?
Thank you.

**Comment by tateomuro** [comment]
Forgot to mention that adding custom filters to the same category they don't affect to custom filters from others categories.

**Comment by Sattva-108** [comment]
There is problem with how 3.3.5 client reads Cyrillic letters. Basically they look like this: `%D0%90%D1`
and original author wanted to use method to remove symbols like:  ` # ` , ` % `.
what for i'm not sure.

problem code:
```lua
local key = gsub(section, "%W", "")
```

In next commit i will just remove this restriction, should be fine !

**Comment by tateomuro** [comment]
Now it's working as I wanted. Thank you.
