### ISSUE TITLE
Ascension again... Sorry...    Getting Items from Cache boxes. 

### ISSUE THREAD

**Issue by Drakcain** [Sattva-108/AdiBags-WoTLK-3.3.5#9]
Date: 2024-02-24 09:00:36
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\modules\ItemLevel.lua line 120:
   attempt to compare number with nil
Debug:
   (tail call): ?
   AdiBags\modules\ItemLevel.lua:120: ?()
   ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145:
      ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145
   [string "safecall Dispatcher[2]"]:4:
      [string "safecall Dispatcher[2]"]:4
   [C]: ?
   [string "safecall Dispatcher[2]"]:13: ?()
   ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: SendMessage()
   AdiBags\widgets\ItemButton.lua:331:
      AdiBags\widgets\ItemButton.lua:306
   [C]: Update()
   AdiBags\widgets\ItemButton.lua:303: FullUpdate()
   AdiBags\widgets\ItemButton.lua:268:
      AdiBags\widgets\ItemButton.lua:256
   [C]: Show()
   AdiBags\widgets\ItemButton.lua:599:
      AdiBags\widgets\ItemButton.lua:581
   (tail call): ?
   AdiBags\widgets\ItemButton.lua:612: Update()
   AdiBags\widgets\ItemButton.lua:570:
      AdiBags\widgets\ItemButton.lua:563
   [C]: Show()
   AdiBags\widgets\Section.lua:250: AddItemButton()
   AdiBags\widgets\ContainerFrame.lua:748: DispatchItem()
   AdiBags\widgets\ContainerFrame.lua:887: RedispatchAllItems()
   AdiBags\widgets\ContainerFrame.lua:1030:
      AdiBags\widgets\ContainerFrame.lua:1017
   (tail call): ?
   AdiBags\widgets\ContainerFrame.lua:443: RefreshContents()
   AdiBags\widgets\ContainerFrame.lua:428: ResumeUpdates()
   AdiBags\widgets\ContainerFrame.lua:411:
      AdiBags\widgets\ContainerFrame.lua:405
   [C]: Show()
   AdiBags\core\Bags.lua:89: Open()
   AdiBags\core\Bags.lua:119:
      AdiBags\core\Bags.lua:115
   (tail call): ?
   (tail call): ?
   [string "TOGGLEBACKPACK"]:1:
      [string "TOGGLEBACKPACK"]:1

**Comment by Drakcain** [comment]
Handle when You have time If your willing., :)

**Comment by Sattva-108** [comment]
https://github.com/Sattva-108/AdiBags-WoTLK-3.3.5/assets/74269253/faed1fcf-9c7e-4740-a4b3-92a81ada6d18

try to do it like this

**Comment by Sattva-108** [comment]
closing this, as this is not this version of adibags issue.
